apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mongo.name }}-secret
type: Opaque
data:
  MONGO_URL: {{ "mongodb://mongo:27017" | b64enc }}
  MONGO_INITDB_ROOT_USERNAME: {{ "admin" | b64enc }}
  MONGO_INITDB_ROOT_PASSWORD: {{ "mongodb_password_123" | b64enc }}
