apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.redis.name }}-secret
type: Opaque
data:
  REDIS_URL: {{ "redis://redis:6379" | b64enc }}
  REDIS_PASSWORD: {{ "redis_password_789" | b64enc }}
