namespace: prod

gateway:
  name: gamesbond-gateway
  gatewayClassName: kgateway
  listener:
    name: http
    protocol: HTTP
    port: 80
    allowedRoutesFrom: Same

route:
  name: gamesbond-route
  parentRefName: gamesbond-gateway

  hostnames:
    - gamesbond.online
    - www.gamesbond.online

  pathPrefix: /
  backend:
    name: frontend-service
    port: 3000