namespace: prod

gateway:
  name: gamesbond-gateway
  className: kgateway

route:
  name: gamesbond-route
  parentRefName: gamesbond-gateway

  hostnames:
    - gamesbond.online
    - www.gamesbond.online

  pathPrefix: /

  backend:
    name: frontend-service
    port: 3000