namespace: dev

gateway:
  name: gamesbond-gateway
  gatewayClassName: kgateway
  listener:
    name: http
    protocol: HTTP
    port: 80
    allowedRoutesFrom: Same

route:
  name: frontend-route
  parentRefName: gamesbond-gateway
  pathPrefix: /
  backend:
    name: frontend
    port: 3000