apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gamesbond-ground-service-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/yourusername/Gamesbond-HelmChart
    targetRevision: main
    path: templates/services/ground-service
    helm:
      values: |
        namespace: dev
        service:
          replicas: 1
          image: maheshnandi/gamesbond-ground-service:v1.0.0
      valueFiles:
      - values.yaml
      - devvalues.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
