apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - mongodb-app.yaml
  - redis-app.yaml
  - network-app.yaml
  - user-service-app.yaml
  - player-service-app.yaml
  - team-service-app.yaml
  - tournament-service-app.yaml
  - ground-service-app.yaml
  - shop-service-app.yaml
  - admin-service-app.yaml
  - frontend-app.yaml
