apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-secret
type: Opaque
data:
  MONGO_URL: {{ "mongodb://mongo:27017" | b64enc }}
  REDIS_URL: {{ "redis://redis:6379" | b64enc }}
  JWT_SECRET: {{ "sports_hub_jwt_secret_456" | b64enc }}
  SESSION_SECRET: {{ "sports_hub_secret_123" | b64enc }}
