apiVersion: v2
name: umbrellahelm
description: An umbrella chart for deploying the entire Gamesbond application
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: admin-service
    version: 0.1.0
    repository: "file://../templates/admin-service"

  - name: database
    version: 0.1.0
    repository: "file://../templates/database"

  - name: frontend-service
    version: 0.1.0
    repository: "file://../templates/frontend-service"

  - name: ground-service
    version: 0.1.0
    repository: "file://../templates/ground-service"

  - name: player-service
    version: 0.1.0
    repository: "file://../templates/player-service"

  - name: shop-service
    version: 0.1.0
    repository: "file://../templates/shop-service"

  - name: team-service
    version: 0.1.0
    repository: "file://../templates/team-service"

  - name: tournament-service
    version: 0.1.0
    repository: "file://../templates/tournament-service"

  - name: user-service
    version: 0.1.0
    repository: "file://../templates/user-service"

  - name: network
    version: 0.1.0
    repository: "file://../templates/network"