global:
  environment: development

admin-service:
  replicaCount: 1

database:
  replicaCount: 1

frontend-service:
  replicaCount: 1

ground-service:
  replicaCount: 1

player-service:
  replicaCount: 1

shop-service:
  replicaCount: 1

team-service:
  replicaCount: 1

tournament-service:
  replicaCount: 1

user-service:
  replicaCount: 1

network:
  replicaCount: 1