apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gamesbond-tournament-service-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/yourusername/Gamesbond-HelmChart
    targetRevision: main
    path: templates/services/tournament-service
    helm:
      values: |
        namespace: prod
        service:
          replicas: 3
          image: maheshnandi/gamesbond-tournament-service:v1.0.0
      valueFiles:
      - values.yaml
      - prodvalues.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
